src/objects/Byt__c.object
<CustomObject>
    <description>Informácie o bytových jednotkách v developerskom projekte.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Zákazník kupujúci si byt</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Byty</relationshipLabel>
        <relationshipName>Byty</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Etapa2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Etapa</label>
        <referenceTo>Etapa__c</referenceTo>
        <relationshipLabel>Byty</relationshipLabel>
        <relationshipName>Byty</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Etapa__c</fullName>
        <label>Etapa</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Etapa 1</fullName>
                </value>
                <value>
                    <fullName>Etapa 2</fullName>
                </value>
                <value>
                    <fullName>Etapa 3</fullName>
                </value>
                <value>
                    <fullName>Etapa 4</fullName>
                </value>
                <value>
                    <fullName>Etapa 5</fullName>
                </value>
                <value>
                    <fullName>Etapa 6</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Izbovos__c</fullName>
        <label>Izbovosť</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1i</fullName>
                </value>
                <value>
                    <fullName>2i</fullName>
                </value>
                <value>
                    <fullName>2,5i</fullName>
                </value>
                <value>
                    <fullName>3i</fullName>
                </value>
                <value>
                    <fullName>3,5i</fullName>
                </value>
                <value>
                    <fullName>4i</fullName>
                </value>
                <value>
                    <fullName>5i</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Ozna_enie__c</fullName>
        <label>Označenie</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Typ__c</fullName>
        <label>Typ</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Byt</fullName>
                    <default>true</default>
                    <label>Byt</label>
                </value>
                <value>
                    <fullName>Apartmán</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Vchod__c</fullName>
        <label>Vchod</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>A</fullName>
                </value>
                <value>
                    <fullName>B</fullName>
                </value>
                <value>
                    <fullName>C</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>slo_ZoBKZ_KZ__c</fullName>
        <label>Číslo ZoBKZ / KZ</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Byt</label>
    <nameField>
        <label>Názov</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Byty</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Etapa__c.object
<CustomObject>
    <fields>
        <fullName>DefinitivnaUzavierka__c</fullName>
        <label>Definitívna uzávierka</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>FixnutieMurovaciek__c</fullName>
        <label>Fixnutie Murovačiek</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>FixnutieProfesii__c</fullName>
        <label>Fixnutie Profesií</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>FixnutieStatiky__c</fullName>
        <label>Fixnutie Statiky</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>UzavierkaKLZ__c</fullName>
        <label>Uzávierka KLZ</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>UzavierkaStandardov__c</fullName>
        <label>Uzávierka štandardov</label>
        <type>Date</type>
    </fields>
    <label>Etapa</label>
    <nameField>
        <label>Etapa Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Etapy</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/EtapyATerminyController.cls
/**
 * Created by juraj on 03/08/2022.
 */

public with sharing class EtapyATerminyController {

    @AuraEnabled(Cacheable=true)
    public static List<AggregateResult> getEtapyList() {

        return [SELECT Name, Id
        FROM Etapa__c GROUP BY Name,Id ORDER BY Name
        ];
    }

    @AuraEnabled
    public static List<Etapa__c> getEtapyNazovList(String etapa) {

        return [SELECT Name, Id, DefinitivnaUzavierka__c, FixnutieMurovaciek__c, FixnutieProfesii__c, FixnutieStatiky__c, UzavierkaKLZ__c, UzavierkaStandardov__c,
                OstavaDniDU__c, OstavaDniFM__c, OstavaDniFP__c, OstavaDniFS__c, OstavaDniUKLZ__c, OstavaDniUS__c
        FROM Etapa__c  WHERE Id =: etapa LIMIT 1
        ];
    }

    @AuraEnabled(Cacheable=true)
    public static List<Byt__c> getBytyListEtapy(String etapa) {
        if (etapa == null) {
            etapa = 'ahpj';
        }
        return [SELECT Id, Etapa__c, Vchod__c, Ozna_enie__c,slo_ZoBKZ_KZ__c, Typ__c, Izbovos__c, Account__c
        FROM Byt__c WHERE Etapa2__c =: etapa
        ];
    }

    @AuraEnabled(Cacheable=true)
    public static List<Etapa__c> getEtapyTerminy(String byt) {

        List<Byt__c> flat = [SELECT Id, Etapa2__r.Id FROM Byt__c WHERE Id =: byt];
        String etapaId = flat[0].Etapa2__r.Id;


        return [SELECT Id, Name, DefinitivnaUzavierka__c, FixnutieMurovaciek__c, FixnutieProfesii__c, FixnutieStatiky__c, UzavierkaKLZ__c, UzavierkaStandardov__c,
                OstavaDniDU__c, OstavaDniFM__c, OstavaDniFP__c, OstavaDniFS__c, OstavaDniUKLZ__c, OstavaDniUS__c
        FROM Etapa__c WHERE Id =: etapaId
        ];
    }

    @AuraEnabled(Cacheable=true)
    public static List<Etapa__c> getUzavretieStandarduTermin(String byt) {

        List<Byt__c> flat = [SELECT Id, Etapa2__r.Id FROM Byt__c WHERE Id =: byt];
        String etapaId = flat[0].Etapa2__r.Id;


        return [SELECT Id,  UzavierkaStandardov__c
        FROM Etapa__c WHERE Id =: etapaId
        ];
    }

}