src/objects/Byt__c.object
<CustomObject>
    <description>Informácie o bytových jednotkách v developerskom projekte.</description>
    <fields>
        <fullName>Ozna_enie__c</fullName>
        <label>Označenie</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Projekt__c</fullName>
        <label>Projekt</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Byt</label>
    <nameField>
        <label>Názov</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Byty</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Byt__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Byt</label>
        <referenceTo>Byt__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/SBQQ__QuoteLine__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/PdfController.cls
/**
 * Created by mgons on 8/2/2022.
 */

public with sharing class PdfController {
    public Byt__c byt{get;set;}
    public String idecko{get;set;}
    public Account acc{get;set;}
    public List<Case> KlzList{get;set;}
    public List<SBQQ__QuoteLine__c> prvkyList{get;set;}

    public PdfController() {
        idecko = getFlatIdForPdf();
        KlzList = KLZController.getKLZ(idecko);
        prvkyList = StandardyController.getJednotlivePrvky(idecko);
        acc = [SELECT Name,Phone,PersonEmail FROM Account WHERE Byt__c =:idecko LIMIT 1];
        byt = [SELECT Projekt__c,Name,Ozna_enie__c FROM Byt__c WHERE Id =:idecko];
    }

    @AuraEnabled
    public static String getFlatIdForPdf(){

        String id;

        Opportunity flatID = [SELECT Id, Description FROM Opportunity WHERE Id = '0061q00000FAsuoAAD'];

        return flatID.Description;
    }

    @AuraEnabled
    public static void setFlatIdForPdf(String flatID){


        Opportunity opportunity = [SELECT Id, Description FROM Opportunity WHERE Id = '0061q00000FAsuoAAD'];
        opportunity.Description = flatID;
        update opportunity;

    }


}