src/objects/Byt__c.object
<CustomObject>
    <description>Informácie o bytových jednotkách v developerskom projekte.</description>
    <fields>
        <fullName>Etapa__c</fullName>
        <label>Etapa</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Etapa 1</fullName>
                </value>
                <value>
                    <fullName>Etapa 2</fullName>
                </value>
                <value>
                    <fullName>Etapa 3</fullName>
                </value>
                <value>
                    <fullName>Etapa 4</fullName>
                </value>
                <value>
                    <fullName>Etapa 5</fullName>
                </value>
                <value>
                    <fullName>Etapa 6</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Vchod__c</fullName>
        <label>Vchod</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>A</fullName>
                </value>
                <value>
                    <fullName>B</fullName>
                </value>
                <value>
                    <fullName>C</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Byt</label>
    <nameField>
        <label>Názov</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Byty</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Etapa__c.object
<CustomObject>
    <label>Etapa</label>
    <nameField>
        <label>Etapa Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Etapy</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PrehladBytovMenuController.cls
/**
 * Created by juraj on 28/07/2022.
 */

public with sharing class PrehladBytovMenuController {

    @AuraEnabled(Cacheable=true)
    public static List<AggregateResult> getVchodyList() {

        return [SELECT Vchod__c
        FROM Byt__c GROUP BY Vchod__c ORDER BY Vchod__c
        ];

    }

    @AuraEnabled(Cacheable=true)
    public static List<AggregateResult> getEtapyList() {

        return [SELECT Name, Id
        FROM Etapa__c GROUP BY Name, Id ORDER BY Name
        ];

    }

}