src/objects/Byt__c.object
<CustomObject>
    <description>Informácie o bytových jednotkách v developerskom projekte.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Zákazník kupujúci si byt</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Byty</relationshipLabel>
        <relationshipName>Byty</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Etapa__c</fullName>
        <label>Etapa</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Etapa 1</fullName>
                </value>
                <value>
                    <fullName>Etapa 2</fullName>
                </value>
                <value>
                    <fullName>Etapa 3</fullName>
                </value>
                <value>
                    <fullName>Etapa 4</fullName>
                </value>
                <value>
                    <fullName>Etapa 5</fullName>
                </value>
                <value>
                    <fullName>Etapa 6</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Izbovos__c</fullName>
        <label>Izbovosť</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1i</fullName>
                </value>
                <value>
                    <fullName>2i</fullName>
                </value>
                <value>
                    <fullName>2,5i</fullName>
                </value>
                <value>
                    <fullName>3i</fullName>
                </value>
                <value>
                    <fullName>3,5i</fullName>
                </value>
                <value>
                    <fullName>4i</fullName>
                </value>
                <value>
                    <fullName>5i</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Ozna_enie__c</fullName>
        <label>Označenie</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Poschodie__c</fullName>
        <label>Poschodie</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Typ__c</fullName>
        <label>Typ</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Byt</fullName>
                    <default>true</default>
                    <label>Byt</label>
                </value>
                <value>
                    <fullName>Apartmán</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Vchod__c</fullName>
        <label>Vchod</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>A</fullName>
                </value>
                <value>
                    <fullName>B</fullName>
                </value>
                <value>
                    <fullName>C</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>slo_ZoBKZ_KZ__c</fullName>
        <label>Číslo ZoBKZ / KZ</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Byt</label>
    <nameField>
        <label>Názov</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Byty</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Etapa__c.object
<CustomObject>
    <label>Etapa</label>
    <nameField>
        <label>Etapa Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Etapy</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PrehladBytovController.cls
/**
 * Created by matistikoff on 21. 7. 2022.
 */

public without sharing class PrehladBytovController {

    @AuraEnabled(Cacheable=true)
    public static List<Byt__c> getBytyList() {
        return [SELECT Id, Etapa__c, Vchod__c, Ozna_enie__c,slo_ZoBKZ_KZ__c, Typ__c, Izbovos__c, Account__c, Poschodie__c
        FROM Byt__c
        ];
    }

    @AuraEnabled(Cacheable=true)
    public static List<Byt__c> getBytyListVchod(String vchod) {
        return [SELECT Id, Etapa__c, Vchod__c, Ozna_enie__c,slo_ZoBKZ_KZ__c, Typ__c, Izbovos__c, Account__c
        FROM Byt__c WHERE Vchod__c =: vchod
        ];
    }

    @AuraEnabled(Cacheable=true)
    public static List<Byt__c> getBytyListEtapy(String etapy) {
        return [SELECT Id, Etapa__c, Vchod__c, Ozna_enie__c,slo_ZoBKZ_KZ__c, Typ__c, Izbovos__c, Account__c
        FROM Byt__c WHERE Etapa__c =: etapy
        ];
    }

    @AuraEnabled(Cacheable=true)
    public static List<Byt__c> getBytyListVchodEtapy(String vchod, String etapy) {
        return [SELECT Id, Etapa__c, Vchod__c, Ozna_enie__c,slo_ZoBKZ_KZ__c, Typ__c, Izbovos__c, Account__c
        FROM Byt__c WHERE Vchod__c =: vchod AND Etapa__c =: etapy
        ];
    }
}