src/objects/Byt__c.object
<CustomObject>
    <description>Informácie o bytových jednotkách v developerskom projekte.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Zákazník kupujúci si byt</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Byty</relationshipLabel>
        <relationshipName>Byty</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>D_tum_podpisu_ZoD_ZoBKZ__c</fullName>
        <label>Dátum podpisu ZoD/ZoBKZ</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Dan_na_rozpo_et__c</fullName>
        <label>Dané na rozpočet</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Etapa__c</fullName>
        <label>Etapa</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Etapa 1</fullName>
                </value>
                <value>
                    <fullName>Etapa 2</fullName>
                </value>
                <value>
                    <fullName>Etapa 3</fullName>
                </value>
                <value>
                    <fullName>Etapa 4</fullName>
                </value>
                <value>
                    <fullName>Etapa 5</fullName>
                </value>
                <value>
                    <fullName>Etapa 6</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Izbovos__c</fullName>
        <label>Izbovosť</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1i</fullName>
                </value>
                <value>
                    <fullName>2i</fullName>
                </value>
                <value>
                    <fullName>2,5i</fullName>
                </value>
                <value>
                    <fullName>3i</fullName>
                </value>
                <value>
                    <fullName>3,5i</fullName>
                </value>
                <value>
                    <fullName>4i</fullName>
                </value>
                <value>
                    <fullName>5i</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Ozna_enie__c</fullName>
        <label>Označenie</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Prijat_zadanie_KLZ__c</fullName>
        <label>Prijaté zadanie KLZ</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Term_n_zaslania_n_vrhu_na_stretnutie__c</fullName>
        <label>Termín zaslania návrhu na stretnutie</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Typ__c</fullName>
        <label>Typ</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Byt</fullName>
                    <default>true</default>
                    <label>Byt</label>
                </value>
                <value>
                    <fullName>Apartmán</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Uz_vierka_tandardov__c</fullName>
        <label>Uzávierka štandardov</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Vchod__c</fullName>
        <label>Vchod</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>A</fullName>
                </value>
                <value>
                    <fullName>B</fullName>
                </value>
                <value>
                    <fullName>C</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Zaslanie_v_zvy_KLZ_najnesk_r_do__c</fullName>
        <label>Zaslanie výzvy KLZ najneskôr do</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>slo_ZoBKZ_KZ__c</fullName>
        <label>Číslo ZoBKZ / KZ</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Byt</label>
    <nameField>
        <label>Názov</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Byty</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Byt__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Byt</label>
        <referenceTo>Byt__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Etapa__c.object
<CustomObject>
    <label>Etapa</label>
    <nameField>
        <label>Etapa Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Etapy</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <fields>
        <fullName>Byt__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Byt</label>
        <referenceTo>Byt__c</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/DashboardController.cls
/**
 * Created by juraj on 25/07/2022.
 */

public without sharing class DashboardController {

    @AuraEnabled(Cacheable=true)
    public static Byt__c getByt(String bytId) {
        return [SELECT Id, Name, Etapa__c, Vchod__c,slo_ZoBKZ_KZ__c, Ozna_enie__c, Typ__c, Izbovos__c, Account__c
        FROM Byt__c WHERE Id=: bytId LIMIT 1];
    }

    @AuraEnabled(Cacheable=true)
    public static List<SBQQ__Quote__c> getStandardy(String bytId){

        List<SBQQ__Quote__c> sb = new List<SBQQ__Quote__c>();

        try {
            sb =[SELECT Id,Name  FROM SBQQ__Quote__c WHERE Byt__c=: bytId];
        } catch (System.QueryException e) {

        }

        return sb;

    }

    @AuraEnabled(Cacheable=true)
    public static List<Case> getKlientskeZmeny(String bytId){

        List<Case> c = new List<Case>();
        try {
             c =  [SELECT Id,OwnerId FROM Case WHERE Byt__c=: bytId];
        } catch (System.QueryException e) {

        }


        return c;
    }

    @AuraEnabled(Cacheable=true)
    public static Byt__c getKontakts(String bytId){
        return [SELECT Id, Account__r.Name,Account__r.Type, Account__r.PersonEmail, Account__r.Phone
        FROM Byt__c
        WHERE Byt__c.Id=: bytId];
    }

    @AuraEnabled(Cacheable=true)
    public static List<Account> getMainContact(String bytId){

        List<Byt__c> acList = [SELECT Id, Account__r.Name, Account__r.Type, Account__r.PersonEmail, Account__r.Phone
        FROM Byt__c
        WHERE Id =: bytId];

        return [SELECT Id,Name, PersonEmail, Phone, Type
        FROM Account
        WHERE Id =: acList[0].Account__r.Id];
    }



    @AuraEnabled(Cacheable=true)

    public static List<Account> getContacts(String bytId){

        List<Account> accList = new List<Account>();
        try {


            List<Byt__c> acc = [SELECT Id,Account__c FROM Byt__c WHERE Id =: bytId];
            List<Account> a = [SELECT Id FROM Account WHERE Id =:acc[0].Account__c];


        List<AccountContactRelation> acr = [SELECT Id, ContactId  FROM AccountContactRelation WHERE AccountId =: a[0].Id];

            accList=  [SELECT Id, Name, PersonContactId
            FROM Account
            WHERE PersonContactId =: acr[0].ContactId];




    }
         catch (System.ListException e) {

        }
        return accList;

    }



    @AuraEnabled(Cacheable=true)
    public static Byt__c getTerminy(String bytId) {

        return [SELECT Id, D_tum_podpisu_ZoD_ZoBKZ__c, Prijat_zadanie_KLZ__c, Zaslanie_v_zvy_KLZ_najnesk_r_do__c, Term_n_zaslania_n_vrhu_na_stretnutie__c, Dan_na_rozpo_et__c, Uz_vierka_tandardov__c
        FROM Byt__c WHERE Id=: bytId];
    }

}