src/objects/Byt__c.object
<CustomObject>
    <description>Informácie o bytových jednotkách v developerskom projekte.</description>
    <label>Byt</label>
    <nameField>
        <label>Názov</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Byty</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Byt__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Byt</label>
        <referenceTo>Byt__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Kalkulacia__c.object
<CustomObject>
    <label>Kalkulácia</label>
    <nameField>
        <label>Názov kalkulácie</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Kalkulácie</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Prvok__c.object
<CustomObject>
    <fields>
        <fullName>Prvok__c</fullName>
        <description>názov prvku</description>
        <label>Prvok</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Bytový rozdelovač</fullName>
                </value>
                <value>
                    <fullName>Chladiaca jednotka</fullName>
                </value>
                <value>
                    <fullName>Dátová zásuvka</fullName>
                </value>
                <value>
                    <fullName>Domáci telefón</fullName>
                </value>
                <value>
                    <fullName>Doplnkové pospájanie</fullName>
                </value>
                <value>
                    <fullName>Elektrická zásuvka</fullName>
                </value>
                <value>
                    <fullName>Elektrická zásuvka s krytom v zateplení</fullName>
                </value>
                <value>
                    <fullName>Elektrický vývod zo steny</fullName>
                </value>
                <value>
                    <fullName>Interiérové dvere</fullName>
                </value>
                <value>
                    <fullName>Keramický obklad</fullName>
                </value>
                <value>
                    <fullName>Kúpeľňové umývadlo</fullName>
                </value>
                <value>
                    <fullName>Ovládanie žaluzii</fullName>
                </value>
                <value>
                    <fullName>Práčkový vývod</fullName>
                </value>
                <value>
                    <fullName>Radiátor</fullName>
                </value>
                <value>
                    <fullName>Rebríkový radiátor</fullName>
                </value>
                <value>
                    <fullName>Rohový ventil</fullName>
                </value>
                <value>
                    <fullName>Spínač jednopólový</fullName>
                </value>
                <value>
                    <fullName>Spínač sériový</fullName>
                </value>
                <value>
                    <fullName>Spínač striedavý</fullName>
                </value>
                <value>
                    <fullName>Sprchová/Vaňová zmiešavacia batéria</fullName>
                </value>
                <value>
                    <fullName>Stropné svietdilo</fullName>
                </value>
                <value>
                    <fullName>Stropné svietidlo</fullName>
                </value>
                <value>
                    <fullName>Umývadlo</fullName>
                </value>
                <value>
                    <fullName>Vchodové dvere</fullName>
                </value>
                <value>
                    <fullName>WC komplet</fullName>
                </value>
                <value>
                    <fullName>Zásuvka 2-rámik</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Prvok</label>
    <nameField>
        <label>Prvok ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prvky</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/NovaKLZController.cls
/**
 * Created by juraj on 01/08/2022.
 */

public with sharing class NovaKLZController {

    @AuraEnabled
    public static String saveCaseRecord(Case objCas, String bytId){
        try{
            objCas.Byt__c = bytId;
            objCas.Status = 'Rozpracovaná';
            insert objCas;
            return objCas.Id;
        }
        catch (Exception ex){
            throw new AuraHandledException(ex.getMessage());
        }
    }

    @AuraEnabled
    public static void updateCaseRecord(String id, String prvok, String internep, String poznamkypk, String status){
        try{

            Case c = new Case();
            c.Id = id;
            c.Prvok__c = prvok;
            c.Interne_poznamky__c = internep;
            c.Poznamka_pre_klienta__c = poznamkypk;
            c.Status = status;
            update c;


        }
        catch (Exception ex){
            throw new AuraHandledException(ex.getMessage());

        }
    }

    @AuraEnabled
    public static void updateAppCaseRecord(String des, String Id){
        try{

            Case c = new Case();
            c.Description = des;
            c.Id = Id;
            update c;

        }
        catch (Exception ex){
            throw new AuraHandledException(ex.getMessage());

        }
    }

    @AuraEnabled
    public static void deleteKalkulacia(String Id){
        try{

            Kalkulacia__c k = new Kalkulacia__c();
            k.Id = Id;
            delete k;

        }
        catch (Exception ex){
            throw new AuraHandledException(ex.getMessage());

        }
    }

    @AuraEnabled
    public static void deleteKlz(String Id){
        try{

            Case c = new Case();
            c.Id = Id;
            delete c;

        }
        catch (Exception ex){
            throw new AuraHandledException(ex.getMessage());

        }
    }

}