src/objects/Byt__c.object
<CustomObject>
    <description>Informácie o bytových jednotkách v developerskom projekte.</description>
    <fields>
        <fullName>Ozna_enie__c</fullName>
        <label>Označenie</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <label>Byt</label>
    <nameField>
        <label>Názov</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Byty</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Byt__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Byt</label>
        <referenceTo>Byt__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/classes/CaseTriggerController.cls
/**
 * Created by matistikoff on 19. 8. 2022.
 */

public with sharing class CaseTriggerController {

    public static void populateKlzIdField(List<Case> cases){

        Map<Id, Case> caseMap = new Map<Id, Case>();
        caseMap.putAll(cases);

        Integer caseCount = [SELECT COUNT() FROM Case WHERE Byt__c =: cases[0].Byt__c];
        Case flatLabel = [SELECT Byt__r.Ozna_enie__c FROM Case WHERE Byt__c =: cases[0].Byt__c LIMIT 1];

        for(Id key: caseMap.keySet()){
            caseMap.get(key).ID_KLZ__c = 'KLZ-'+flatLabel.Byt__r.Ozna_enie__c+'-'+(++caseCount);
            caseCount++;
        }
    }
}