src/objects/Etapa__c.object
<CustomObject>
    <fields>
        <fullName>DefinitivnaUzavierka__c</fullName>
        <label>Definitívna uzávierka</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>FixnutieMurovaciek__c</fullName>
        <label>Fixnutie Murovačiek</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>FixnutieProfesii__c</fullName>
        <label>Fixnutie Profesií</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>FixnutieStatiky__c</fullName>
        <label>Fixnutie Statiky</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>UzavierkaKLZ__c</fullName>
        <label>Uzávierka KLZ</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>UzavierkaStandardov__c</fullName>
        <label>Uzávierka štandardov</label>
        <type>Date</type>
    </fields>
    <label>Etapa</label>
    <nameField>
        <label>Etapa Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Etapy</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/EtapyUpdate.cls
/**
 * Created by juraj on 17/08/2022.
 */

public with sharing class EtapyUpdate {

    @AuraEnabled
    public static void updateEtapa(String id, Date us, Date uklz, Date fp, Date fs, Date fm, Date du, String name){

        try{
            Etapa__c e = new Etapa__c();
            e.Id = id;
            e.Name = name;
            e.UzavierkaStandardov__c = us;
            e.UzavierkaKLZ__c = uklz;
            e.FixnutieProfesii__c = fp;
            e.FixnutieStatiky__c = fs;
            e.FixnutieMurovaciek__c = fm;
            e.DefinitivnaUzavierka__c = du;
            update e;

        }
        catch (Exception ex){
            throw new AuraHandledException(ex.getMessage());

        }
    }
}