src/objects/Miestnost__c.object
<CustomObject>
    <fields>
        <fullName>Byt__c</fullName>
        <label>Byt</label>
        <referenceTo>Byt__c</referenceTo>
        <relationshipLabel>Miestnosti</relationshipLabel>
        <relationshipName>Miestnosti</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Miestnosť</label>
    <nameField>
        <label>Miestnosť ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Miestnosti</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Miestnos__c</fullName>
        <label>Miestnosť</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Miestnosti</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Image_Link__c</fullName>
        <inlineHelpText>URL zdroju obrázka</inlineHelpText>
        <label>Product Image Link</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Image__c</fullName>
        <formula>IMAGE( Product_Image_Link__c ,&quot;&quot;,50,50)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Image</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Prvok__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Prvok</label>
        <referenceTo>Prvok__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__DefaultQuantity__c</fullName>
        <defaultValue>1</defaultValue>
        <description>Specifies the starting quantity of the product when added.</description>
        <inlineHelpText>Specify the starting quantity of the product when added.</inlineHelpText>
        <label>Default Quantity</label>
        <precision>18</precision>
        <scale>5</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Produkt_Prvku__c.object
<CustomObject>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Produkty Prvku</relationshipLabel>
        <relationshipName>Produkty_Prvku</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Prvok__c</fullName>
        <label>Prvok</label>
        <referenceTo>Prvok__c</referenceTo>
        <relationshipLabel>Produkty Prvku</relationshipLabel>
        <relationshipName>Produkty_Prvku</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Produkt Prvku</label>
    <nameField>
        <label>Produkt Prvku Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Produkty Prvku</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/SBQQ__ProductOption__c.object
<CustomObject>
    <customHelpPage>SBQQ__ProductOptionHelp</customHelpPage>
    <description>Option for a configurable product.</description>
    <fields>
        <fullName>Miestnos__c</fullName>
        <label>Miestnosť</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Miestnosti</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Image_Link__c</fullName>
        <formula>SBQQ__OptionalSKU__r.Product_Image_Link__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Image Link</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Image__c</fullName>
        <formula>IMAGE( Product_Image_Link__c ,&quot;&quot;,50,50)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Image</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SBQQ__ConfiguredSKU__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Product SKU of the bundle that is being configured with this option. If you create the option from the product detail page, this should already be populated.</description>
        <inlineHelpText>Product SKU of the bundle that is being configured with this option. If you create the option from the product detail page, this should already be populated.</inlineHelpText>
        <label>Configured SKU</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Options</relationshipLabel>
        <relationshipName>Options</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Feature__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Feature that selects this option.</description>
        <inlineHelpText>Enter or lookup the feature that includes this option. This will be dependent on the Configured SKU.</inlineHelpText>
        <label>Feature</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.SBQQ__ConfiguredSKU__c</field>
                <operation>equals</operation>
                <valueField>SBQQ__ProductFeature__c.SBQQ__ConfiguredSKU__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>SBQQ__ProductFeature__c</referenceTo>
        <relationshipLabel>Product Options</relationshipLabel>
        <relationshipName>ProductOptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__MaxQuantity__c</fullName>
        <description>Maximum quantity allowed for this option.</description>
        <inlineHelpText>Maximum quantity allowed for this option.</inlineHelpText>
        <label>Max Quantity</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SBQQ__Number__c</fullName>
        <description>Sequential number that determines this option&apos;s sort order.</description>
        <inlineHelpText>Set the display order of this option within the feature it&apos;s assigned to.</inlineHelpText>
        <label>Number</label>
        <precision>5</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SBQQ__OptionalSKU__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Product SKU added if this option is selected.</description>
        <inlineHelpText>Enter or lookup the product SKU that should be added when this product is selected.</inlineHelpText>
        <label>Optional SKU</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Optional For</relationshipLabel>
        <relationshipName>OptionalFor</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__ProductFamily__c</fullName>
        <description>Product Family for the optional product SKU.</description>
        <formula>TEXT(SBQQ__OptionalSKU__r.Family)</formula>
        <inlineHelpText>Product Family for the optional product SKU.</inlineHelpText>
        <label>Product Family</label>
        <type>Text</type>
    </fields>
    <label>Product Option</label>
    <nameField>
        <displayFormat>PO-{000000}</displayFormat>
        <label>Option Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Options</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <fields>
        <fullName>Byt__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Byt</label>
        <referenceTo>Byt__c</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SBQQ__QuoteLine__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <fields>
        <fullName>Miestnos__c</fullName>
        <label>Miestnosť</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Miestnosti</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Image__c</fullName>
        <formula>SBQQ__Product__r.Product_Image__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Image</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SBQQ__Number__c</fullName>
        <description>Number indicating this line&apos;s position within its group or quote.</description>
        <inlineHelpText>Number indicating this line&apos;s position within its group or quote.</inlineHelpText>
        <label>Number</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SBQQ__ProductFamily__c</fullName>
        <description>How you would categorize/group/organize this within Salesforce (whether it&apos;s a new or existing Product Family). Additionally, this field can be used during product selection to filter to the correct product or product SKU.</description>
        <formula>TEXT(SBQQ__Product__r.Family)</formula>
        <inlineHelpText>How you would categorize/group/organize this within Salesforce (whether it&apos;s a new or existing Product Family). Additionally, this field can be used during product selection to filter to the correct product or product SKU.</inlineHelpText>
        <label>Product Family</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SBQQ__ProductOption__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Product option that generated this line (if any).</description>
        <inlineHelpText>Product option that generated this line (if any).</inlineHelpText>
        <label>Product Option</label>
        <referenceTo>SBQQ__ProductOption__c</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>Quote_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Product quoted by this line item.</description>
        <inlineHelpText>Product quoted by this line item.</inlineHelpText>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>R00N70000001lXB6EAM</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <description>Quote to which this line item belongs.</description>
        <inlineHelpText>Quote to which this line item belongs.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>LineItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/StandardyController.cls
/**
 * Created by matistikoff on 10. 8. 2022.
 */

public without sharing class StandardyController {


    @AuraEnabled
    public static List<SBQQ__QuoteLine__c> getLineItems(String lineId) {
        return [
                SELECT Id, Miestnos__c, SBQQ__ProductFamily__c, SBQQ__Product__r.Name
                FROM SBQQ__QuoteLine__c
                WHERE SBQQ__QuoteLine__c.SBQQ__Quote__r.Byt__r.Id = :lineId AND Miestnos__c != NULL
        ];
    }

    @AuraEnabled
    public static List<SBQQ__QuoteLine__c> getLineItemsMiestnost(String lineId, String miestnost) {
        return [
                SELECT Id, Miestnos__c, SBQQ__ProductFamily__c, SBQQ__Product__r.Name
                FROM SBQQ__QuoteLine__c
                WHERE SBQQ__QuoteLine__c.SBQQ__Quote__r.Byt__r.Id = :lineId AND Miestnos__c != NULL AND Miestnos__c = :miestnost
        ];
    }

    @AuraEnabled
    public static List<SBQQ__QuoteLine__c> getLineItemsProdukt(String lineId, String product) {
        return [
                SELECT Id, Miestnos__c, SBQQ__ProductFamily__c, SBQQ__Product__r.Name
                FROM SBQQ__QuoteLine__c
                WHERE SBQQ__QuoteLine__c.SBQQ__Quote__r.Byt__r.Id = :lineId AND Miestnos__c != NULL AND SBQQ__ProductFamily__c = :product
        ];
    }


    @AuraEnabled
    public static AggregateResult getLineCount(String lineId) {
        AggregateResult ar =
                (AggregateResult) [
                        SELECT COUNT(Id)
                        FROM SBQQ__QuoteLine__c
                        WHERE SBQQ__QuoteLine__c.SBQQ__Quote__r.Byt__r.Id = :lineId
                ];
        return ar;
    }

    @AuraEnabled
    public static List<AggregateResult> getDistinctRooms(String lineId) {
        List<AggregateResult> ar = [
                SELECT COUNT(Id), Miestnos__c
                FROM SBQQ__QuoteLine__c
                WHERE SBQQ__QuoteLine__c.SBQQ__Quote__r.Byt__r.Id = :lineId
                GROUP BY Miestnos__c
        ];
        return ar;
    }

    //soql queries po prekopani standardov

    @AuraEnabled
    public static Id getFlatIdAsProduct(String flatID) {
        SBQQ__QuoteLine__c quoteLine = [
                SELECT Id, Miestnos__c, SBQQ__ProductFamily__c, SBQQ__Product__r.Name, SBQQ__Product__r.Id
                FROM SBQQ__QuoteLine__c
                WHERE SBQQ__QuoteLine__c.SBQQ__Quote__r.Byt__r.Id = :flatID AND SBQQ__Number__c = 1
                LIMIT 1
        ];

        return quoteLine.SBQQ__Product__r.Id;

    }

    @AuraEnabled
    public static List<SBQQ__ProductFeature__c> getFlatStandards(String flatID) {
        SBQQ__QuoteLine__c quoteLine = [
                SELECT Id, Miestnos__c, SBQQ__ProductFamily__c, SBQQ__Product__r.Name, SBQQ__Product__r.Id
                FROM SBQQ__QuoteLine__c
                WHERE SBQQ__QuoteLine__c.SBQQ__Quote__r.Byt__r.Id = :flatID AND SBQQ__Number__c = 1
                LIMIT 1
        ];

        Id flatIdAsProduct = quoteLine.SBQQ__Product__r.Id;

        List<SBQQ__ProductFeature__c> standards = [SELECT Id, Name, SBQQ__ConfiguredSKU__r.Id FROM SBQQ__ProductFeature__c WHERE SBQQ__ConfiguredSKU__r.Id = :flatIdAsProduct];

        return standards;

    }

    @AuraEnabled
    public static List<SBQQ__ProductOption__c> getStandardsForRooms(String flatIdAsProduct, String featureID) {

        List<SBQQ__ProductOption__c> standardsForRooms = [
                SELECT Id, Name, SBQQ__ConfiguredSKU__r.Id, SBQQ__OptionalSKU__r.Name, SBQQ__Feature__r.Id, SBQQ__OptionalSKU__r.Id
                FROM SBQQ__ProductOption__c
                WHERE SBQQ__ConfiguredSKU__r.Id = :flatIdAsProduct AND SBQQ__Feature__r.Id = :featureID
        ];

        return standardsForRooms;

    }

    @AuraEnabled
    public static List<SBQQ__ProductFeature__c> getProductsFromStandard(String standardID) {

        List<SBQQ__ProductFeature__c> productTypes =

        [
                SELECT Id, Name, SBQQ__ConfiguredSKU__r.Id, SBQQ__MaxOptionCount__c, SBQQ__ConfiguredSKU__r.Name
                FROM SBQQ__ProductFeature__c
                WHERE SBQQ__ConfiguredSKU__r.Id = :standardID
        ];

        return productTypes;

    }


    @AuraEnabled
    public static List<wrapProduct> getFeaturesFromProducts(String standardID, String featureID, String flatID) {


        List<wrapProduct> wrapProducts = new List<wrapProduct>();
        SBQQ__ProductOption__c selectedProduct = new SBQQ__ProductOption__c();

        try {
            SBQQ__QuoteLine__c quoteLine = [
                    SELECT Id, Name, SBQQ__Product__r.Name, SBQQ__ProductOption__r.SBQQ__ConfiguredSKU__r.Id, SBQQ__ProductOption__r.SBQQ__Feature__r.Id
                    FROM SBQQ__QuoteLine__c
                    WHERE SBQQ__Quote__r.Byt__c = :flatID AND SBQQ__ProductOption__r.SBQQ__ConfiguredSKU__r.Id = :standardID AND SBQQ__ProductOption__r.SBQQ__Feature__r.Id = :featureID
                    LIMIT 1
            ];

            selectedProduct = [
                    SELECT Id, Name, SBQQ__ConfiguredSKU__r.Id, SBQQ__ConfiguredSKU__r.Name, SBQQ__MaxQuantity__c, Product_Image__c, Product_Image_Link__c, SBQQ__OptionalSKU__r.Name, SBQQ__Feature__r.Name
                    FROM SBQQ__ProductOption__c
                    WHERE Id = :quoteLine.SBQQ__ProductOption__c
            ];
            wrapProducts.add(new wrapProduct(selectedProduct, true));
        } catch (QueryException e) {
            System.debug(e.getMessage());
        }


        List<SBQQ__ProductOption__c> productFeatures = [
                SELECT Id, Name, SBQQ__ConfiguredSKU__r.Id, SBQQ__ConfiguredSKU__r.Name, SBQQ__MaxQuantity__c, Product_Image__c, Product_Image_Link__c, SBQQ__OptionalSKU__r.Name, SBQQ__Feature__r.Name
                FROM SBQQ__ProductOption__c
                WHERE SBQQ__ConfiguredSKU__r.Id = :standardID
                AND SBQQ__Feature__r.Id = :featureID
        ];

        for (Integer i = 0; i < productFeatures.size(); i++) {
            if (productFeatures[i] == selectedProduct) {
                productFeatures.remove(i);
            } else {
                wrapProducts.add(new wrapProduct(productFeatures[i], false));
            }

        }

        return wrapProducts;
    }


    @AuraEnabled
    public static String insertProduct(String flatID, List<String> selectedIds, String prvokID) {

        SBQQ__Quote__c quote = [SELECT Id, Byt__c FROM SBQQ__Quote__c WHERE Byt__c = :flatID];
        List<SBQQ__QuoteLine__c> quoteLines = new List<SBQQ__QuoteLine__c>();
        Product2 mainProduct2 = [SELECT Id, Name, SBQQ__DefaultQuantity__c FROM Product2 WHERE Id = :selectedIds.get(selectedIds.size() - 1)];
        Prvok__c prvok = [SELECT Id, Miestnost__r.NazovMiestnosti__c FROM Prvok__c WHERE Id = :prvokID];
        Produkt_Prvku__c produktPrvku = [SELECT Mnozstvo__c FROM Produkt_Prvku__c WHERE Prvok__c =: prvokID AND Product__c =: mainProduct2.Id];
        List<SBQQ__QuoteLine__c> checkForSamePart = new List<SBQQ__QuoteLine__c>();

        List<String> selectedIdsWithoutDuplicates = new List<String>();
        for (String id : selectedIds) {
            if (!selectedIdsWithoutDuplicates.contains(id)) {
                selectedIdsWithoutDuplicates.add(id);
            }
        }

        for(Integer i = 0; i < produktPrvku.Mnozstvo__c; i++){

        for (String id : selectedIdsWithoutDuplicates) {

            Id sId = id;
            String sobjectType = sId.getSobjectType().getDescribe().getName();

            if (sobjectType == 'SBQQ__ProductOption__c') {
                SBQQ__ProductOption__c option = [
                        SELECT Id, Name, SBQQ__Quantity__c, CastPrvku__c, SBQQ__ConfiguredSKU__r.Id, Product_Image__c, SBQQ__OptionalSKU__r.Name, SBQQ__Feature__r.Name, SBQQ__OptionalSKU__r.Id
                        FROM SBQQ__ProductOption__c
                        WHERE Id = :id
                ];


                try {
                    checkForSamePart = [SELECT Id, Name, SBQQ__Quote__r.Byt__c, Miestnos__c, CastPrvku__c, Prvok__r.Prvok__c, SBQQ__Product__r.Name
                    FROM SBQQ__QuoteLine__c
                    WHERE Prvok__c =: prvokID
                    AND CastPrvku__c =: option.CastPrvku__c];

                } catch (QueryException e) {

                }

                if (checkForSamePart.size() == 1){
                    delete checkForSamePart;
                }

                SBQQ__QuoteLine__c quoteLine = new SBQQ__QuoteLine__c();
                quoteLine.SBQQ__Quote__c = quote.Id;
                quoteLine.SBQQ__Product__c = option.SBQQ__OptionalSKU__r.Id;
                quoteLine.SBQQ__ProductOption__c = option.Id;
                quoteLine.SBQQ__Quantity__c = option.SBQQ__Quantity__c;
                quoteLine.Prvok__c = prvokID;
                quoteLine.Miestnos__c = prvok.Miestnost__r.NazovMiestnosti__c;
                quoteLines.add(quoteLine);
            } else {

                try {
                    List<SBQQ__QuoteLine__c> checkForDuplicate = [
                            SELECT Id, Name, SBQQ__Quote__r.Byt__c, Miestnos__c, CastPrvku__c, Prvok__r.Prvok__c, SBQQ__Product__r.Name
                            FROM SBQQ__QuoteLine__c
                            WHERE Prvok__c = :prvokID
                            AND SBQQ__Product__r.Id = :mainProduct2.Id
                    ];

                    if (checkForDuplicate.size() == 0) {
                        SBQQ__QuoteLine__c quoteLine = new SBQQ__QuoteLine__c();
                        quoteLine.SBQQ__Quote__c = quote.Id;
                        quoteLine.SBQQ__Product__c = mainProduct2.Id;
                        quoteLine.SBQQ__Quantity__c = mainProduct2.SBQQ__DefaultQuantity__c;
                        quoteLine.Prvok__c = prvokID;
                        quoteLine.Miestnos__c = prvok.Miestnost__r.NazovMiestnosti__c;
                        quoteLines.add(quoteLine);
                    }
                } catch (Exception e) {

                }
            }


        }
        }

        insert quoteLines;
        return 'Duplikat';

    }


    /**
  standardy po tretej prerabke
  @author miso
    */

    @AuraEnabled
    public static void deleteQuoteLines(String prvokID) {

        List<SBQQ__QuoteLine__c> quoteLinesToDelete = [SELECT Id, Name FROM SBQQ__QuoteLine__c WHERE Prvok__c = :prvokID];
        delete quoteLinesToDelete;
    }

    @AuraEnabled(Cacheable=true)
    public static List<Miestnost__c> getMiestnosti(String flatID) {
        return [SELECT Id, NazovMiestnosti__c, Byt__c FROM Miestnost__c WHERE Byt__c = :flatID];
    }

    @AuraEnabled(Cacheable=true)
    public static List<Prvok__c> getPrvky(String MiestnostID) {


        return [SELECT Id, Miestnost__c, Prvok__c, Name FROM Prvok__c WHERE Miestnost__c = :MiestnostID];
    }

    @AuraEnabled
    public static List<wrapProductPrvku> getProduktPrvky(String prvokID) {

        List<wrapProductPrvku> wraps = new List<wrapProductPrvku>();
        List<Produkt_Prvku__c> produktyPrvku = [SELECT Id, Prvok__c, Product__r.Name, Product__r.Id, Product__r.Product_Image_Link__c, Product__r.CastPrvku__c, Vybrany__c, Uroven__c FROM Produkt_Prvku__c WHERE Prvok__c = :prvokID ORDER BY Uroven__c];

        List<SBQQ__QuoteLine__c> quoteLines = [SELECT Name, Prvok__c, SBQQ__Product__r.Name FROM SBQQ__QuoteLine__c WHERE Prvok__c = :produktyPrvku[0].Prvok__c];

        Produkt_Prvku__c selectedPrvok;


        for (Produkt_Prvku__c prvok : produktyPrvku) {
            for (SBQQ__QuoteLine__c quoteLineL : quoteLines) {
                if (prvok.Product__r.Name == quoteLineL.SBQQ__Product__r.Name) {
                    selectedPrvok = prvok;
                    wraps.add(new wrapProductPrvku(prvok, true));
                    break;
                }

            }
        }

        for (Integer i = 0; i < produktyPrvku.size(); i++) {
            System.debug('halo ' + produktyPrvku);

            if (produktyPrvku[i] == selectedPrvok) {
                produktyPrvku.remove(i);
            }
         else {
        wraps.add(new wrapProductPrvku(produktyPrvku[i], false));
    }
        }




        return wraps;
    }

    @AuraEnabled(Cacheable=true)
    public static Miestnost__c getMiestnostName(String prvokID) {

        return [SELECT Id, NazovMiestnosti__c FROM Miestnost__c WHERE Id = :prvokID];

    }

    @AuraEnabled(Cacheable=true)
    public static Prvok__c getProduktPrvkuName(String prvokID) {

        return [SELECT Id, Prvok__c FROM Prvok__c WHERE Id = :prvokID];

    }

    @AuraEnabled
    public static String updateProduktPrvku(String prvokID) {


        Produkt_Prvku__c prvok = [SELECT Id, Vybrany__c, Prvok__c FROM Produkt_Prvku__c WHERE Id = :prvokID];
        try {
            Produkt_Prvku__c prvokToDeactivate = [SELECT Id, Vybrany__c, Prvok__c FROM Produkt_Prvku__c WHERE Prvok__c = :prvok.Prvok__c AND Vybrany__c = TRUE];
            prvokToDeactivate.Vybrany__c = false;
            update prvokToDeactivate;
        } catch (QueryException e) {
            System.debug(e.getMessage());
        }
        prvok.Vybrany__c = true;
        update prvok;
        return prvok.Id;

    }

    @AuraEnabled
    public static String getActivatedPrvokID(String prvokID) {


        try {
            Produkt_Prvku__c prvok = [SELECT Id, Vybrany__c, Prvok__c FROM Produkt_Prvku__c WHERE Prvok__c = :prvokID AND Vybrany__c = TRUE];
            return prvok.Id;
        } catch (QueryException e) {
            System.debug(e.getMessage());
        }

        return null;

    }

    @AuraEnabled
    public static Boolean checkForActivatedPrvok(String prvokID, String productID) {


        try {
            Produkt_Prvku__c prvok = [SELECT Id, Vybrany__c, Prvok__c FROM Produkt_Prvku__c WHERE Prvok__c = :prvokID AND Vybrany__c = TRUE];
            Produkt_Prvku__c selectedPrvok = [SELECT Id, Vybrany__c, Prvok__c, Product__r.Id FROM Produkt_Prvku__c WHERE Product__r.Id =: productID];

            if (selectedPrvok.Vybrany__c == false){
                return false;
            }
            else {
                return true;
            }
        } catch (QueryException e) {
            System.debug(e.getMessage());
        }

        return null;

    }


    @AuraEnabled
    public static List<wrapProductOptions> getProductOptions(String productID, List<String> selectedIds, String prvokID) {

        List<wrapProductOptions> wrapProductOptions = new List<wrapProductOptions>();
        List<SBQQ__ProductOption__c> productOptions2 = new List<SBQQ__ProductOption__c>();
        List<String> vybrane = new List<String>();


        try {
            List<SBQQ__QuoteLine__c> quoteLines = [SELECT Name, Prvok__c, SBQQ__ProductOption__c, SBQQ__ProductOption__r.SBQQ__OptionalSKU__r.Name FROM SBQQ__QuoteLine__c WHERE Prvok__c = :prvokID];

            for (SBQQ__QuoteLine__c quoteLine : quoteLines) {
                if (quoteLine.SBQQ__ProductOption__c != null) {
                    selectedIds.add(quoteLine.SBQQ__ProductOption__c);
                }
            }

            for (String id : selectedIds) {
                Id sId = id;
                String sobjectType = sId.getSobjectType().getDescribe().getName();
                if (id != null && sobjectType != 'Product2') {
                    SBQQ__ProductOption__c productOption = [SELECT SBQQ__Feature__r.Name FROM SBQQ__ProductOption__c WHERE Id = :id];
                    vybrane.add(productOption.SBQQ__Feature__r.Name);
                }

            }
        } catch (QueryException e) {

        }

        try {
            List<AggregateResult> productOptions = (List<AggregateResult>) [SELECT COUNT(Id), SBQQ__Feature__r.Name FROM SBQQ__ProductOption__c WHERE SBQQ__ConfiguredSKU__c = :productID GROUP BY SBQQ__Feature__r.Name];

            for (AggregateResult pro : productOptions) {


                if (vybrane.contains((String) pro.get('Name'))) {
                    wrapProductOptions.add(new wrapProductOptions(pro, 'VYBRANY'));
                } else {
                    wrapProductOptions.add(new wrapProductOptions(pro, 'NEVYBRANY'));
                }


            }


            return wrapProductOptions;
        } catch (QueryException e) {
            System.debug(e.getMessage());
        }

        return null;
    }

    @AuraEnabled(Cacheable=true)
    public static Integer getVybrany(String productID, List<String> selectedIds, String prvokID) {

        List<wrapProductOptions> wrapProductOptions = new List<wrapProductOptions>();
        List<SBQQ__ProductOption__c> productOptions2 = new List<SBQQ__ProductOption__c>();
        List<String> vybrane = new List<String>();
        Integer num = 0;


        try {
            List<SBQQ__QuoteLine__c> quoteLines = [SELECT Name, Prvok__c, SBQQ__ProductOption__c, SBQQ__ProductOption__r.SBQQ__OptionalSKU__r.Name FROM SBQQ__QuoteLine__c WHERE Prvok__c = :prvokID];

            for (SBQQ__QuoteLine__c quoteLine : quoteLines) {
                if (quoteLine.SBQQ__ProductOption__c != null) {
                    selectedIds.add(quoteLine.SBQQ__ProductOption__c);
                }
            }

            for (String id : selectedIds) {
                Id sId = id;
                String sobjectType = sId.getSobjectType().getDescribe().getName();
                if (id != null && sobjectType != 'Product2') {
                    SBQQ__ProductOption__c productOption = [SELECT SBQQ__Feature__r.Name FROM SBQQ__ProductOption__c WHERE Id = :id];
                    vybrane.add(productOption.SBQQ__Feature__r.Name);
                }

            }
        } catch (QueryException e) {

        }

        try {
            List<AggregateResult> productOptions = (List<AggregateResult>) [SELECT COUNT(Id), SBQQ__Feature__r.Name FROM SBQQ__ProductOption__c WHERE SBQQ__ConfiguredSKU__c = :productID GROUP BY SBQQ__Feature__r.Name];

            for (AggregateResult pro : productOptions) {


                if (vybrane.contains((String) pro.get('Name'))) {
                    wrapProductOptions.add(new wrapProductOptions(pro, 'VYBRANY'));
                    num++;
                } else {
                    wrapProductOptions.add(new wrapProductOptions(pro, 'NEVYBRANY'));
                }


            }


            return num;
        } catch (QueryException e) {
            System.debug(e.getMessage());
        }

        return null;
    }


    @AuraEnabled
    public static List<wrapProduct> getConcreteProductOptions(String productID, String featureName, List<String> selectedIds, String prvokID) {

        List<wrapProduct> wrapProducts = new List<wrapProduct>();
        List<SBQQ__QuoteLine__c> quoteLines = [SELECT Name, Prvok__c, SBQQ__ProductOption__c, SBQQ__ProductOption__r.SBQQ__OptionalSKU__r.Name FROM SBQQ__QuoteLine__c WHERE Prvok__c = :prvokID];

        for (SBQQ__QuoteLine__c quoteLine : quoteLines) {
            selectedIds.add(quoteLine.SBQQ__ProductOption__c);
        }



        try {
            List<SBQQ__ProductOption__c> productOptions = [SELECT Name, SBQQ__ConfiguredSKU__c, CastPrvku__c, SBQQ__OptionalSKU__r.Id, SBQQ__OptionalSKU__r.Name, SBQQ__Feature__r.Name, Product_Image_Link__c FROM SBQQ__ProductOption__c WHERE SBQQ__ConfiguredSKU__c = :productID AND SBQQ__Feature__r.Name = :featureName];


            for (Integer i = 0; i < productOptions.size(); i++) {

                if (selectedIds.contains(productOptions[i].Id)) {




                    wrapProducts.add(new wrapProduct(productOptions[i], true));
                } else {
                    wrapProducts.add(new wrapProduct(productOptions[i], false));
                }

            }

            return wrapProducts;
        } catch (QueryException e) {
            System.debug(e.getMessage());
        }

        return null;
    }

    @AuraEnabled
    public static String checkIfConcreteIsSelected(String productID, String featureName, List<String> selectedIds, String prvokID) {

        List<wrapProduct> wrapProducts = new List<wrapProduct>();
        List<SBQQ__QuoteLine__c> quoteLines = [SELECT Name, Prvok__c, SBQQ__ProductOption__c, SBQQ__ProductOption__r.SBQQ__OptionalSKU__r.Name FROM SBQQ__QuoteLine__c WHERE Prvok__c = :prvokID];

        for (SBQQ__QuoteLine__c quoteLine : quoteLines) {
            selectedIds.add(quoteLine.SBQQ__ProductOption__c);
        }



        try {
            List<SBQQ__ProductOption__c> productOptions = [SELECT Name, SBQQ__ConfiguredSKU__c, CastPrvku__c, SBQQ__OptionalSKU__r.Id, SBQQ__OptionalSKU__r.Name, SBQQ__Feature__r.Name, Product_Image_Link__c FROM SBQQ__ProductOption__c WHERE SBQQ__ConfiguredSKU__c = :productID AND SBQQ__Feature__r.Name = :featureName];


            for (Integer i = 0; i < productOptions.size(); i++) {

                if (selectedIds.contains(productOptions[i].Id)) {
                    return 'vybrany';




                } else {
                    wrapProducts.add(new wrapProduct(productOptions[i], false));
                }

            }

            return 'nevybrany';
        } catch (QueryException e) {
            System.debug(e.getMessage());
        }

        return null;
    }

    @AuraEnabled
    public static String getActivatedProductOptions(String productID, String featureName, List<String> selectedIds, String prvokID) {

        List<wrapProduct> wrapProducts = new List<wrapProduct>();
        List<SBQQ__QuoteLine__c> quoteLines = [SELECT Name, Prvok__c, SBQQ__ProductOption__c, SBQQ__ProductOption__r.SBQQ__OptionalSKU__r.Name FROM SBQQ__QuoteLine__c WHERE Prvok__c = :prvokID];

        for (SBQQ__QuoteLine__c quoteLine : quoteLines) {
            selectedIds.add(quoteLine.SBQQ__ProductOption__c);
        }



        try {
            List<SBQQ__ProductOption__c> productOptions = [SELECT Name, SBQQ__ConfiguredSKU__c, CastPrvku__c, SBQQ__OptionalSKU__r.Id, SBQQ__OptionalSKU__r.Name, SBQQ__Feature__r.Name, Product_Image_Link__c FROM SBQQ__ProductOption__c WHERE SBQQ__ConfiguredSKU__c = :productID AND SBQQ__Feature__r.Name = :featureName];


            for (Integer i = 0; i < productOptions.size(); i++) {

                if (selectedIds.contains(productOptions[i].Id)) {
                    return productOptions[i].Id;


                } else {
                    wrapProducts.add(new wrapProduct(productOptions[i], false));
                }

            }

            return null;
        } catch (QueryException e) {
            System.debug(e.getMessage());
        }

        return null;


    }


    @AuraEnabled
    public static Integer getNumberOfPrvky(String mainProductId) {

        List<AggregateResult> productOptions = (List<AggregateResult>) [SELECT COUNT(Id), Name FROM SBQQ__ProductFeature__c WHERE SBQQ__ConfiguredSKU__c = :mainProductId GROUP BY Name];

        Integer num = 0;
        for (AggregateResult arr : productOptions) {
            num += (Integer) arr.get('expr0');
        }
        return num;
    }


    @AuraEnabled
    public static List<Product2> getSelectedProducts(List<String> selectedIds) {

        List<Product2> products = new List<Product2>();

        List<String> selectedIdsWithoutDuplicates = new List<String>();
        for (String id : selectedIds) {
            if (!selectedIdsWithoutDuplicates.contains(id)) {
                selectedIdsWithoutDuplicates.add(id);
            }
        }

        for (String id : selectedIdsWithoutDuplicates) {

            Id sId = id;
            String sobjectType = sId.getSobjectType().getDescribe().getName();

            if (sobjectType == 'SBQQ__ProductOption__c') {
                SBQQ__ProductOption__c productOption = [SELECT Name, SBQQ__ConfiguredSKU__c, SBQQ__OptionalSKU__r.Name, SBQQ__Feature__r.Name, Product_Image_Link__c, SBQQ__OptionalSKU__r.Id FROM SBQQ__ProductOption__c WHERE Id = :id];
                Product2 product2 = [SELECT Id, Name, Product_Image_Link__c FROM Product2 WHERE Id = :productOption.SBQQ__OptionalSKU__c];
                products.add(product2);
            } else {
                Product2 product2 = [SELECT Id, Name, Product_Image_Link__c FROM Product2 WHERE Id = :id];
                products.add(product2);
            }
        }

        return products;
    }

    @AuraEnabled
    public static List<SBQQ__QuoteLine__c> getJednotlivePrvky(String flatID) {

        return [
                SELECT Id, Name, SBQQ__Quote__r.Byt__c, Miestnos__c, CastPrvku__c,Prvok__r.Name, Prvok__r.Prvok__c, SBQQ__Product__r.Name,SBQQ__ListPrice__c
                FROM SBQQ__QuoteLine__c
                WHERE SBQQ__Quote__r.Byt__c = :flatID
        ];

    }


    public class wrapProduct {

        @AuraEnabled
        public SBQQ__ProductOption__c productOption { get; set; }
        @AuraEnabled
        public Boolean selected { get; set; }

        //This is the contructor method. When we create a new wrapAccount object we pass a Account that is set to the acc property. We also set the selected value to false
        public wrapProduct(SBQQ__ProductOption__c a, Boolean b) {
            productOption = a;
            selected = b;
        }
    }

    public class wrapProductOptions {

        @AuraEnabled
        public AggregateResult aggregateResult { get; set; }
        @AuraEnabled
        public String vybrane { get; set; }

        //This is the contructor method. When we create a new wrapAccount object we pass a Account that is set to the acc property. We also set the selected value to false
        public wrapProductOptions(AggregateResult a, String b) {
            aggregateResult = a;
            vybrane = b;
        }
    }
    public class wrapProductPrvku {

        @AuraEnabled
        public Produkt_Prvku__c produktPrvku { get; set; }
        @AuraEnabled
        public Boolean vybrane { get; set; }

        public wrapProductPrvku(Produkt_Prvku__c a, Boolean b) {
            produktPrvku = a;
            vybrane = b;
        }
    }

}